var SequenceSum = (function (){

  function SequenceSum (){}

  	SequenceSum.showSequence = function(count) {
  		for (i = 0; i <= count; i++){
  			var x = showSequence(6).toString();
  			
  			console.log(x);
  		}


  		SequenceSum.showSequence(6);//"0+1+2+3+4+5+6 = 21"
  		//SequenceSum.showSequence(-15);//-15<0
  		//SequenceSum.showSequence(0);//0
  };
  return SequenceSum;
})();

/*

Required - A function that computes the series from 0 to ending following two sequences.

Two approaches:
- One is to count the sum generated by the num

What you need:
- A Loop that will increment 1 to the gven number
- A Loop that will write down the sum

*/